rename bootstrap scripts

diff --git a/bin/repos/init b/bin/repos/init
--- a/bin/repos/init
+++ b/bin/repos/init
@@ -3,8 +3,9 @@
 
 # find script location
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-# shellcheck source=./lib/bashopts.sh
-source "${DIR}/../lib/bashopts.sh"
+
+# shellcheck source=${DIR}/../../lib/bashopts.sh
+source "${DIR}/../../lib/bashopts.sh"
 
 banner
 
@@ -17,7 +18,8 @@ banner
 ###############################################################################
 help() {
    # Display Help
-   echo "read .repo-manifest file, iterate list of repos, clone or update each."
+   echo "read .repo-manifest file, iterate list of repos, authorize direnv and execute"
+   echo "the default make target for each."
    echo
    echo "Syntax: scriptTemplate [-h|v]"
    echo "options:"
@@ -29,6 +31,7 @@ help() {
 ###############################################################################
 # Process the input options. Add options as needed.
 ###############################################################################
+# Get the options
 while getopts ":hv" option; do
    case $option in
       h) # display Help
@@ -36,11 +39,12 @@ while getopts ":hv" option; do
         exit
         ;;
       v) # set verbose flag
-        echo "Enabling debug mode" && set -x
+        DEBUG
         ;;
 
      \?) # invalid option
-        die "Error: Invalid option"
+        echo "Error: Invalid option"
+        exit
         ;;
    esac
 done
@@ -48,13 +52,21 @@ done
 ###############################################################################
 # Main function
 ###############################################################################
-while IFS= read -r line
-do
-  org=$(echo "$line" | cut -d/ -f1)
-  [[ -z "$org" ]] && die "malformed repo manifest entry"
+main() {
+  while IFS= read -r repo
+  do
+    # org=$(echo "$repo" | cut -d/ -f1)
+    repo=$(echo "$repo" | cut -d/ -f2)
+    echo ""
+    echo "$repo"
+    echo "####################################################################"
+    (
+      cd "${REPO_PATH}/$repo" || exit
+      [[ -f .envrc ]] && direnv allow
+      [[ -f Makefile ]] && make
+      : # true
+    )
+  done <<< "$(cat "${DIR}/../../.repo-manifest")"
+}
 
-  repo=$(echo "$line" | cut -d/ -f2)
-  [[ -z "$repo" ]] && die "malformed repo manifest entry"
-
-  git_clone_or_update "git@github.com:$org/$repo.git" "${REPO_PATH}/$repo"
-done <<< "$(cat "${DIR}/../.repo-manifest")"
+main "$@"
